#!/bin/sh
# Run to build distribution packages and upload them to pypi

# Stop on errors
set -e

cd "$(dirname "$0")/.."

# Remove previous build
if [ -n "$(ls | grep 'build')" ]; then
	rm -r build/
fi

# Upgrade setuptools to the latest version
python3 -m pip install --upgrade setuptools

# Install missing dependencies
if [ -z "$(python3 -m pip list | grep 'wheel')" ]; then
	python3 -m pip install wheel
fi
if [ -z "$(python3 -m pip list | grep 'twine')" ]; then
	python3 -m pip install twine
fi

echo "====================================="
echo "=   Generation source distribution  ="
echo "====================================="
python3 setup.py sdist

echo "===================================="
echo "=   Generation build distribution  ="
echo "===================================="
python3 setup.py bdist_wheel

echo "====================="
echo "=   Upload to pypi  ="
echo "====================="
python3 -m twine upload dist/* --skip-existing
